config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "shops#welcome"


  resources :shops do
  		resources :shelves, :candies
	end

	resources :candies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candy.rb
class Candy < ApplicationRecord
  	belongs_to :shop

  	validates_presence_of :name

end

app/models/shelf.rb
class Shelf < ApplicationRecord
  	belongs_to :shop

  	has_many :candies

end

app/models/shop.rb
class Shop < ApplicationRecord
	has_many :shelves
	has_many :candies

	validates_associated :candies
	
	after_initialize :init

	def init
		self.num_of_shelves = 0 
	end	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/candies_controller.rb
class CandiesController < ApplicationController

	def create
		@shop = Shop.find(1)
		@candy = @shop.candies.create(candy_params)
		redirect_to shop_path(@shop)
		
	end

	def edit
		@candy = Candy.find(params[:id])
		@shelves = Shelf.all
	end

	def update
		@shelves = Shelf.all
		@candy = Candy.find(params[:id])

		@previous_shelf_location = @candy.belongs_to_shelf

		if(@candy.update(candy_params))
			@search = Shelf.where(id: @candy.belongs_to_shelf)
			if @candy.belongs_to_shelf == nil
				redirect_to @candy
			elsif @search.blank?
				@candy.belongs_to_shelf = @previous_shelf_location
				@candy.save
				render 'edit'
			else
				redirect_to @candy
			end
		else
			render 'edit'
		end
	end

	def destroy
		@candy = Post.find(params[:id])
		@candy.destroy

		redirect_to @candy
	end

	def show
		@candy = Candy.find(params[:id])
	end

	def candy_params
		candy_params = params.require(:candy).permit(:name, :belongs_to_shelf)
	end

end

app/controllers/shelves_controller.rb
class ShelvesController < ApplicationController
	
	def index
		@shop = Shop.find(1)
		@shelves = Shelf.all()
	end

	def create
		@shop = Shop.find(1)
		@shop.num_of_shelves += 1
		@shop.save
		
		@shelf = @shop.shelves.create()
		redirect_to shop_shelves_path(@shop)
	end

	def show
		@shop = Shop.find(1)
		@shelf = Shelf.find(params[:id])
	end

	def destroy
		@shop = Shop.find(params[:shop_id])
    	@shelf = Shelf.find(params[:id])

    	Candy.where(belongs_to_shelf: @shelf.id).find_each do |candy|
    		candy.belongs_to_shelf = nil
    		candy.save
    	end

    	@shelf.destroy

    	redirect_to shop_shelves_path(1)
	end

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController

	def welcome

	end

	def create
		@shop = Shop.new

		if(@shop.save)
			redirect_to @shop
		else
			render 'new'
		end
	end

	def show
		@shop = Shop.find(1)
	end

	def update
	 	@shop = Shop.find(1)
	 	if @shop.update!(shop_params)
	    	redirect_to @shop
	 	else
	    	render 'edit'
	  	end
	end

	def shop_params
  		shop_params = params.require(:shop).permit(:num_of_shelves ,candies_attributes: [:name, :belongs_to_shelf, :shelf_id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candies_helper.rb
module CandiesHelper
end

app/helpers/shelves_helper.rb
module ShelvesHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/candies/_candies.html.erb
<div class = "well">
	<h3>List of Candies in Shop:</h3>

	<% @shop.candies.each do |candy| %>
		<p><strong><%= candy.name %></strong></p>
		<%= link_to "View Candy Details", candy_path(candy) , :class => 'btn btn-default' %>
	<% end %>

</div>

<div class = "well">
	<h3>List of Unshelved Candies in Shop:</h3>

	<% @shop.candies.where(belongs_to_shelf: nil).find_each do |candy| %>
		<p><strong><%= candy.name %></strong></p>
	<% end %>
</div>

app/views/candies/_form.html.erb
<div class = "well">
	<h3>Add Candy</h3>  
	<%= form_for([@shop, @shop.candies.build]) do |f| %>
		<% if @shop.errors.any? %>
		    <% @shop.errors.full_messages.each do |message| %>
		      <li><%= message %></li>
		    <% end %>
		  <% end %>
		  
		<p>
			<%= f.label :name %><br>
			<%= f.text_field(:name,:required => true, :class => 'form-control') %>
		</p>
	  

		<p>
			<%= f.submit({:class => 'btn btn-primary'}) %>
		</p>
		 
	<% end %>

</div>

app/views/candies/edit.html.erb
<h1>Move Candy</h1>
<p>To move a candy to a shelf, please enter the number of the shelf. Ex: '1', '2', '3', etc. and select 'Move Candy'.</p>
<p>To unshelf a candy, leave the following field blank and select 'Move Candy'. </p>

<hr>

<p>The following shelves are available in the shop. If no shelf is available, please select 'Create Shelf' from the 'Candy Shop' page.</p>

<% @shelves.each do |shelf| %>
	<p>Shelf #<%= shelf.id %></p>
<% end %>


<hr>

<%= form_for :candy, url: candy_path(@candy), method: :patch do |f| %>
	<% if @candy.errors.any? %>
		<% @candy.errors.full_messages.each do |msg| %>
			<div class = "aler alert-danger"><%= msg %></div>
		<% end %>
	<% end %>

	<p>
		<%= f.label :move_to_shelf %><br>
		<%= f.text_area(:belongs_to_shelf, {:class => 'form-control'}) %>
	</p>
  
	<p>
		<%= f.submit 'Move Candy', class: "btn btn-primary" %>
	</p>
 
<% end %>

app/views/candies/show.html.erb
<h1>Candy Name: <%= @candy.name%></h1>
<p>Belongs to Shelf: <%= @candy.belongs_to_shelf %></p>

<%= link_to "Move Candy", edit_shop_candy_path(@candy) , :class => 'btn btn-default' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Candyshop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://bootswatch.com/3/cerulean/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

 <body>

    <nav class="navbar navbar-default">
    <div class ="container">
      <div class ="navbar-header">
        <button type ="button" class ="navbar-toggle collapsed" data-toggle="collapse" data-target="navbar" aria-expanded ="false" aria-controls = "navbar">
          <span class = "sr-only">Toggle navigation</span>
          <span class = "icon bar"></span>
          <span class = "icon bar"></span>
          <span class = "icon bar"></span>
        </button>
      </div>
      <div id ="navbar" class = "collapse navbar-collapse">
        <u1 class = "nav navbar-nav">
          <li><%= link_to "Candy Shop", shop_path(1) %></li>
          <li><%= link_to "Shelves", shop_shelves_path(1) %></li>
        </u1>
      </div>
    </div>
  </nav>

  <div class="container">
        <%= yield %>
  </div>

  </body>
</html>

app/views/shelves/_form.html.erb
<div class = "well">
	<h3>Add Shelf</h3>  
	<%= form_for([@shop, @shop.shelves.build]) do |f| %>
		<p>
			<%= f.submit({:class => 'btn btn-primary'}) %>
		</p>
	<% end %>
</div>

app/views/shelves/index.html.erb
<h1>Shelves</h1>

<% @shelves.each do |shelf| %>
	<div class="well">
		<h1>Shelf #<%= shelf.id %></h1>
		<%= link_to "Visit Shelf", shop_shelf_path(@shop, shelf), :class => 'btn btn-primary' %>
	</div>
<% end %>

app/views/shelves/show.html.erb
<h1>Shelf #<%= @shelf.id%></h1>

<p>Number of Candies: <%= Candy.where(:belongs_to_shelf => @shelf.id).count %> </p>

<hr>

<p>List of Candies in Shelf: </p>

<% @shop.candies.where(belongs_to_shelf: @shelf.id).find_each do |candy| %>
	<p><strong><%= candy.name %></strong></p>
<% end %>

<hr>

<%= link_to "Remove Shelf", shop_shelf_path(@shelf.shop, @shelf),
				method: :delete, 
				data: {confirm: 'Are you sure?'},

				:class => 'btn btn-danger' %>

<hr>

app/views/shops/new.html.erb
<h1>Welcome to the Candy Shop</h1>
<h4>To begin your visit, please select 'Enter Shop'</h4>
<%= form_for :shop, url: shops_path do |f| %>
	<p>
		<%= f.submit 'Enter Shop', class: "btn btn-primary" %>
	</p>
 
<% end %>

app/views/shops/show.html.erb
<h1>Shop Details</h1>

<div class = "well">
	<h3>Number of Shelves in Shop: <%=@shop.shelves.count %></h3>
</div>


<%= render 'candies/candies' %>
<%= render 'candies/form' %>
<%= render 'shelves/form' %>

app/views/shops/welcome.html.erb
<h1>Welcome to the Candy Shop</h1>
<h4>To begin your visit, please select 'Enter Shop'</h4>
<%= form_for :shop, url: shops_path do |f| %>
	<p>
		<%= f.submit 'Enter Shop', class: "btn btn-primary" %>
	</p>
<% end %>